name: card_scanner
description: A new Flutter project.
homepage: https://demo.com
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies: 
  collection: ^1.17.2
  credit_card_scanner: ^1.0.5
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  flutter_secure_storage: ^9.0.0
  go_router: ^10.0.0
  golden_toolkit: ^0.15.0
  http: ^1.1.0 # This package is used for the local server (if not used, can be removed)
  jaguar_jwt: ^3.0.0 # This package is used for the local server (if not used, can be removed)
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  provider: ^6.0.5
  retrofit: ^4.0.1
  rx_bloc: ^5.0.0
  rx_bloc_list: ^4.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  shelf: ^1.4.1 # This package is used for the local server (if not used, can be removed)
  shelf_router: ^1.1.4 # This package is used for the local server (if not used, can be removed)
  shelf_static: ^1.1.2 # This package is used for the local server (if not used, can be removed)
  widget_toolkit: ^0.0.2-dev.1

dev_dependencies:
  build_runner: ^2.4.6
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2 
  r_flutter: 0.9.0
  retrofit_generator: ^7.0.8
  rx_bloc_generator: ^7.0.0
  rx_bloc_test: ^4.0.0
  test: any 


  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500

r_flutter:
  intl: lib/l10n/arb/en.arb
  intl_features:
    - name: error
    - name: field
    - name: lib_router
    - name: lib_change_language
    - name: feature_scanner
    - name: feature_success

